#!/usr/bin/env python3.8

import os
import json
from lgbm_titanic.training import train_model

if __name__ == "__main__":
    train_model(
        train_data_path=os.environ.get("SM_CHANNEL_TRAIN"),
        validation_data_path=os.environ.get("SM_CHANNEL_VALIDATION"),
        save_model_path=os.environ.get("SM_MODEL_DIR"),
        model_params=json.loads(os.environ.get("SM_HPS", "{}")),
    )
